# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lXUhwuwaDhcq332BooabILsFK4sDXGix

faça um programa que pessa uma nota, entre zero e dez. mostre uma mensagem caso o valor seja invalido
"""

nota = float(input("digite uma nota entre zero e dez: "))
while nota > 10 or nota < 0:
  nota = float(input("digite um valor valido"))
print("sucesso")

"""escreva um programa e solicite ao usuario que insira um numero e, em seguida imprima o numero da taboada ate dez"""

numero = int(input("digite um numero "))
contador = 1
while contador <= 10:
  resultado = numero * contador
  print(f"{numero} x {contador} = {resultado}")
  contador += 1

"""crie um programaque leia um nome de usuário e a sua senha e não aceite a
senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando
a pedir as informações.
"""

usuario = (input("digite nome de usuario"))
senha = (input("digite uma senha"))
while senha == usuario:
  print("digite uma senha diferente do nome de usuario")
  senha = input("digite uma senha")
else:
 print("bem vindo nao esqueca a senha e  nem o  ")

"""escreva um programa que conte de 1 a 10 e imprima cada número."""

numero = int(input("digite um numero "))
contador = 1
while contador <= 10:
  resultado = numero + contador
  print(f"{numero} + {contador} = {resultado}")
  contador += 1

"""Escreva um programa que imprima os números pares de 1 a 20."""

numero = 2
while numero <= 20:
  print(numero)
  numero += 2

"""Escreva um programa que solicite ao usuário que insira um número e, em
seguida, imprima todos os números de 1 até esse número.
"""

numero = int(input("digite um numero "))
contador = 1
while contador <= numero:
 print(contador)
 contador += 1

"""Escreva um programa que solicite ao usuário que insira um número e, em
seguida, imprima todos os números pares de 2 até esse número.
"""

numero = int(input("digite um numero "))
contador = 2
while contador <= numero:
 print(contador)
 contador += 2

"""Escreva um programa que solicite ao usuário que insira uma senha. O
programa deve continuar solicitando a senha até que o usuário insira a senha
correta.
"""

senha = 756899
inserir = int(input("Digite uma senha"))
while senha != inserir:
 print("Digite a senha correta")
 inserir = int(input("Digite uma senha"))
else:
  print("senha correta")

"""Escreva um programa que calcule a média de uma lista de números fornecida
pelo usuário.
"""

numero = int(input("digite um numero:"))
soma = 0
contador = 0
while contador < numero:
  numero = int(input("digite um numero para soma: "))
  soma += numero2
  contador += 1
  resultado = soma / numero
  print(f"o resultado e: {resultado}")

"""Escreva um programa que solicite ao usuário que insira números até que ele
insira o número 0. Em seguida, imprima a soma de todos os números inseridos.
"""

soma = 0
numero = int(input("digite um numero (0 encerra): "))
while numero !=3232 0:
 soma += numero
 numero = int(input("digite um numero (0 encerra): "))
 print(f"a soma dos dos numeros e {soma}")

"""Escreva um programa que solicite ao usuário que insira números até que ele
insira um número negativo. Em seguida, imprima o maior número inserido.
"""

maiornumero = 0
numero = int(input(" digite um numero(numero negativo encerra: "))
while numero >= 0:
  numero = int(input(" digite um numero(numero negativo encerra: "))
  if numero > maiornumero:
    maiornumero = numero
print(f"o maior numero e {maiornumero}")
